//! The Unicode character data of the compiler and its Unicode version.
//!
//! The module owns the Unicode properties that the Rust language contract
//! reads and the version they come from. Module `tables` is generated by
//! `tools/unicode-tables.rs` from the pinned Unicode Character Database file
//! and is not edited by hand. Callers receive character classes; the tables
//! stay private.

mod tables;

use std::cmp::Ordering;

/// The Unicode version of the identifier character classes: Unicode 17.0.0,
/// from `[ident.unicode]` of the Rust Reference for Rust 1.99.0.
///
/// It is a Fernq language-contract value. It changes with the reference
/// toolchain, not with the host compiler or a dependency.
pub(crate) const IDENTIFIER_UNICODE_VERSION: (u8, u8, u8) = (17, 0, 0);

// The tables must carry the contract version; a regeneration from another
// Unicode version fails the build.
const _: () = assert!(
    tables::UNICODE_VERSION.0 == IDENTIFIER_UNICODE_VERSION.0
        && tables::UNICODE_VERSION.1 == IDENTIFIER_UNICODE_VERSION.1
        && tables::UNICODE_VERSION.2 == IDENTIFIER_UNICODE_VERSION.2,
    "the generated tables are not of the identifier Unicode version"
);

/// Whether `c` has the Unicode property `XID_Start`.
pub(crate) fn is_xid_start(c: char) -> bool {
    if c.is_ascii() {
        return c.is_ascii_alphabetic();
    }
    contains(tables::XID_START, c)
}

/// Whether `c` has the Unicode property `XID_Continue`.
pub(crate) fn is_xid_continue(c: char) -> bool {
    if c.is_ascii() {
        return c.is_ascii_alphanumeric() || c == '_';
    }
    contains(tables::XID_CONTINUE, c)
}

/// Whether one of the sorted, non-overlapping inclusive ranges of `table`
/// contains `c`.
fn contains(table: &[(char, char)], c: char) -> bool {
    table
        .binary_search_by(|&(lo, hi)| {
            if hi < c {
                Ordering::Less
            } else if lo > c {
                Ordering::Greater
            } else {
                Ordering::Equal
            }
        })
        .is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn non_ascii_count(predicate: fn(char) -> bool) -> usize {
        ('\u{80}'..=char::MAX).filter(|&c| predicate(c)).count()
    }

    #[test]
    fn each_table_is_sorted_non_overlapping_and_non_adjacent() {
        for table in [tables::XID_START, tables::XID_CONTINUE] {
            assert!(!table.is_empty());
            for &(lo, hi) in table {
                assert!(lo <= hi, "{lo:?}..={hi:?}");
            }
            for pair in table.windows(2) {
                let [(_, previous_hi), (lo, _)] = pair else {
                    unreachable!("windows(2) yields pairs");
                };
                assert!(
                    u32::from(*previous_hi) + 1 < u32::from(*lo),
                    "{previous_hi:?} and {lo:?}"
                );
            }
        }
    }

    #[test]
    fn xid_start_is_a_subset_of_xid_continue() {
        for c in '\0'..=char::MAX {
            assert!(!is_xid_start(c) || is_xid_continue(c), "{c:?}");
        }
    }

    #[test]
    fn ascii_lookups_agree_with_the_ascii_identifier_classes() {
        for c in '\0'..='\u{7F}' {
            assert_eq!(is_xid_start(c), c.is_ascii_alphabetic(), "{c:?}");
            assert_eq!(
                is_xid_continue(c),
                c.is_ascii_alphanumeric() || c == '_',
                "{c:?}"
            );
            assert_eq!(contains(tables::XID_START, c), is_xid_start(c), "{c:?}");
            assert_eq!(
                contains(tables::XID_CONTINUE, c),
                is_xid_continue(c),
                "{c:?}"
            );
        }
    }

    #[test]
    fn the_non_ascii_classes_have_the_unicode_17_counts() {
        assert_eq!(non_ascii_count(is_xid_start), 145_841);
        assert_eq!(non_ascii_count(is_xid_continue), 149_158);
    }

    #[test]
    fn classifies_the_probe_characters() {
        for (c, start, continue_) in [
            ('\u{0C5C}', true, true),
            ('\u{0558}', false, false),
            ('\u{037A}', false, false),
            ('\u{2E2F}', false, false),
            ('\u{200C}', false, true),
            ('\u{200D}', false, true),
            ('\u{30FB}', false, true),
            ('\u{0301}', false, true),
            ('\u{1F600}', false, false),
            ('\u{212A}', true, true),
        ] {
            assert_eq!(is_xid_start(c), start, "{c:?}");
            assert_eq!(is_xid_continue(c), continue_, "{c:?}");
        }
    }
}
